# This function was generated by Gemini
def print_lane_path(path):
    print("\n" + "="*55)
    print(" 🎳 LANE PATH VISUALIZATION (Top-Down) 🎳")
    print("="*55)
    print("      LEFT                               RIGHT")
    print("      39                  20                 1")
    print("      |.......................................|")
    
    # Step backwards from 60ft to 0ft in 2-foot increments
    for target_y in range(60, -1, -2):
        # Find the coordinate in the path closest to this exact distance
        closest_point = min(path, key=lambda p: abs(p[0] - target_y))
        board_x = closest_point[1]
        
        # Default lane background
        row_chars = ['.'] * 39
        
        # Draw Arrows around 14ft-16ft
        if target_y == 14 or target_y == 16:
            for arrow in [5, 10, 15, 20, 25, 30, 35]:
                arrow_idx = int(39 - arrow) # Mirror for visual Left/Right
                row_chars[arrow_idx] = '^'
                
        # Draw the Ball ('O')
        if board_x < 0.5: 
            # Right Gutter
            row_str = "".join(row_chars) + "O"
        elif board_x > 39.5: 
            # Left Gutter
            row_str = "O" + "".join(row_chars)
        else:
            # On the Lane
            char_idx = int(39 - round(board_x)) # Convert board 1-39 to string index 38-0
            row_chars[char_idx] = 'O'
            row_str = " " + "".join(row_chars) + " "

        # Add zone labels
        label = ""
        if target_y == 60: label = " <-- PINS / IMPACT"
        elif target_y == 40: label = " <-- PATTERN END"
        elif target_y == 16: label = " <-- ARROWS"
        elif target_y == 0:  label = " <-- FOUL LINE"
        
        # Print the row
        print(f"{target_y:02d}ft |{row_str}|{label}")
        
    print("="*55 + "\n")

def print_pin_deck_result(deck, hit_log):
    """
    Takes the simulation results from the PinDeck and formats them 
    into a clean terminal output, including strike/spare analysis.
    """
    if hit_log:
        for log in hit_log:
            print(log)
        print("-" * 55)
    
        # Check the total count
        pins_down = len(hit_log)    
        if pins_down == 10:
            print(" ❌ STRIKE! ❌")
        else:
            # Find which pins are still standing
            standing_pins = [str(pin.id) for pin in deck.pins if pin.is_standing]
            print(f" Count: {pins_down} | Left Standing: {', '.join(standing_pins)}")
    else:
        # Corrected from 10 to 0 for a complete miss/gutter
        print("-" * 55)
        print(" Count: 0 | Left Standing: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10")

    print("=" * 55 + "\n")